### ISSUE TITLE
New challenge doesn't have 'updated' field value

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#103]
@ThomasKranitsas  - On the challenge UI, we are now showing that New tab, which shows new challenges.  The problem is that we sort the challenges by `updated`.  

### Problem
Currently, the challenge API doesn't set the updated value when the challenge is created

So, on a new challenge, only created is available, not updated.  Normally, I like to design that sort of thing so that for a newly created object, both created and updated are just set to the same value

### Fix

When a challenge is created initially, please set the `updated` and `updatedBy` values to the same as the ones used for `created` and `createdBy`.

### Example of the current problem
```
    {
        "id": "d8a90e2d-ba49-48c1-9c62-7fd64cf8265b",
        "created": "2020-05-01T22:38:06.945Z",
        "createdBy": "TonyJ",
        "status": "New",
        "projectId": 6583,
        "name": "Justin Test 7",
        "startDate": "2020-05-02T22:38:06.000Z",
        "terms": [],
        "groups": [],
        "numOfSubmissions": 0,
        "numOfRegistrants": 0,
        "numberOfRegistrants": 0,
        "type": "Code"
    }
```

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/challenge-api/commit/1ea6990a1cd16b68621233d50c4e1a6adbf1fdf3
