### ISSUE TITLE
Can't PATCH the phases properly

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#105]
@ThomasKranitsas - This one's lower priority, but we should be able to PATCH the phases with full information, similar to what we get when they are filled in fully.

Right now, it won't let us patch beyond the phase ID and duration.  

Error seen:

```
{"message":"\"id\" is not allowed, \"actualStartDate\" is not allowed, \"scheduledStartDate\" is not allowed, \"name\" is not allowed, \"scheduledEndDate\" is not allowed, \"isOpen\" is not allowed"}
```

**Comment by ThomasKranitsas** [comment]
@rootelement thoughts on this? All fields other than `id` and `duration` are auto-calculated before saved in dynamo/ES. 
Perhaps we can auto-calculate those on `POST` but let the user update those in `PUT/PATCH`?

**Comment by rootelement** [comment]
I think it should auto-calculate if the fields don't exist. Is that possible?

**Comment by rootelement** [comment]
This is fixed. The Create/Update function on Challenge API now "sanitizes" fields that it does not want to process.
