### ISSUE TITLE
PATCH not always applying immediately

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#106]
@ThomasKranitsas / @rootelement  - This is from a member working on the v5 integration into Topcoder-X.  I've also had complaints about similar issues when we've been working on the challenge UI.

Let me report a problem in the v5 challenge API.

The problem related to the API PATCH /challenges/{id} to partially update a challenge data. I have to make two attempts of requests to see that the data is updated. The first request is success and returned the right data, but if we get the data with GET /challenges/{id}, the data won't be updated.

https://drive.google.com/open?id=1Q1E9KbhZUTLANWilUHcm5mq-X-fZ17zt

This might affect my verification. The affected features are updating price, title, and description, activating challenge, and closing challenge.

**Comment by ThomasKranitsas** [comment]
@rootelement this has to be related to the issues we were having with the ES processor which was not picking up the Kafka messages.

**Comment by ThomasKranitsas** [comment]
Fixed
