### ISSUE TITLE
Adding group failing in the challenge API

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#115]
@ThomasKranitsas - @rootelement  and I were discussing this one a bit today:

### Currently

I am unable to PATCH in any groups into a challenge.  With `TonyJ`, I can make a request like this:

PATCH `{"groups":["TestGroup"]}`

But the response is always

403 `You don't have access to this group!`

### Expected

We discussed with the Groups API copilot, and we're going to update the groups list to be populated with a call like:

GET `https://api.topcoder-dev.com/v5/groups?memberId=8547899&membershipType=user`

Which *should* return the groups that the user has access to (in this case `TonyJ`)

Those groups should be able to be PATCH'd into a challenge by the same user.

### Related

https://github.com/topcoder-platform/challenge-engine-ui/issues/242

**Comment by jmgasper** [comment]
I'm not sure if `ensureAcessibilityToModifiedGroups` is working correctly, but it's a bit convoluted so I can't know for sure.

**Comment by ThomasKranitsas** [comment]
Fixed
