### ISSUE TITLE
Problem with metadata saving

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#118]
@ThomasKranitsas @jmgasper there is one backend problem.

- First time i update allowStockArt and send PATCH request with body:
```
[{name: "allowStockArt", value: "true"}]
```
-> SUCCESS

- Second time i update submissionsViewable and send PATCH request with body:
```
{"metadata":[{"name":"submissionsViewable","value":"true"},{"name":"allowStockArt","value":"true"}]}
```
Backend throw error:
```
{"message":"\"metadata\" position 1 contains a duplicate value"}
```

But if i only send new update field it is success but it will replace old value. For example i only send:
```
{"metadata":[{"name":"submissionsViewable","value":"true"}]}
```
Then after reload page and get project info again the backend only return:

```
...
{"metadata":[{"name":"submissionsViewable","value":"true"}]}
...
```
The expected result should be:
```
...
{"metadata":[{"name":"submissionsViewable","value":"true"},{"name":"allowStockArt","value":"true"}]}
...
```

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/challenge-api/commit/e1f1ef15f21ff90a182039c6b672f23833921a92
