### ISSUE TITLE
Can't search partial words in challenge name

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#124]
We can't seem to search partial words in the challenge name.

### Works and returns lots of `test` challenges:

https://api.topcoder-dev.com/v5/challenges?sortBy=updated&sortOrder=desc&name=test&projectId=6583&status=Active&page=1&perPage=50&memberId=8547899

### Returns an empty array when searching for name=`tes`

https://api.topcoder-dev.com/v5/challenges?sortBy=updated&sortOrder=desc&name=tes&projectId=6583&status=Active&page=1&perPage=50&memberId=8547899

We had a similar issue in the projects-api, and they added the ability to search with `*`, like `*tes*`

**Comment by rootelement** [comment]
This issue in and of itself is fixed. The search is definitely fuzzy now. But it's very vague. There will be a related issue opened to make the search more intelligent across not only name, but challenge description and tags
