### ISSUE TITLE
Internal Server Error on POST

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#125]
I'm attempting to create a new challenge, and the request is failing with a 500 / `Internal Server Error` response.

Note that a second attempt seemed to work, with the same POST.

@ThomasKranitsas -
Can we include more details about what went wrong in the response please?  Seems like that would help with debugging

### Request

POST  https://api.topcoder-dev.com/v5/challenges
`
{"status":"New","projectId":"6583","name":"Justin NDA test","typeId":"0b2ac310-eaf0-40e3-b66b-37e5e9e09365","startDate":"2020-05-13T17:43:05+10:00","legacy":{"track":"DEVELOP","reviewType":"community"},"timelineTemplateId":"7ebf1c69-f62f-4d3a-bdfb-fe9ddb56861c","terms":["ae6fc4ff-3bd1-4e3f-a987-cc60ab94b422"],"phases":[{"duration":172800,"phaseId":"aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b"},{"duration":259200,"phaseId":"a93544bc-c165-4af4-b55e-18f3593b457a"},{"duration":86400,"phaseId":"797a6af7-cd3f-4436-9fca-9679f773bee9"},{"duration":86400,"phaseId":"1c24cfb3-5b0a-4dbd-b6bd-4b0dff5349c6"},{"duration":259200,"phaseId":"6950164f-3c5e-4bdc-abc8-22aaf5a1bd49"}]}
`

**Comment by rootelement** [comment]
I believe this can be closed
