### ISSUE TITLE
Listing pages are breaking for the logged in user

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#130]
**Steps**

1. Access challenge listing with login user(`dan_developer / dantopcoder123`) 
https://test-community-app.topcoder-dev.com/challenges

2. It doesn't load challenges, they were working before but now it has an error in the console 
**Call failing :** https://api.topcoder-dev.com/v5/challenges/?status=Active&perPage=50&page=1

**Error :**
{"message":"\"organizationId\" is required"}

**Screenshot : ** 

![Topcoder Challenges 2020-05-22 15-34-33](https://user-images.githubusercontent.com/683231/82656687-ce874400-9c41-11ea-81b7-1e114042ad7b.png)

**Comment by SathyaJayabal** [comment]
@rootelement , This issue is seen for certain users like dan_developer/appirio123 , tester1234/appirio123 and nithyaasworld/appirio123. 

But the challenges are loading fine for some users like TonyJ/appirio123 and Mess/appirio123
cc @sushilshinde

**Comment by rootelement** [comment]
@SathyaJayabal that's because TonyJ and Mess are administrators. I'd stay away from testing with them. `dan_developer` and `cori_copilot` are probably the best to test with.

**Comment by rootelement** [comment]
Duyshant was doing testing on the v5 groups api and made `organizationId` required. This has been made optional which unblocks this. Please test again @SathyaJayabal

**Comment by lakshmiathreya** [comment]
Listing working fine for logged in user dan_developer:
<img width="1652" alt="Screenshot 2020-05-23 at 9 25 54 PM" src="https://user-images.githubusercontent.com/51733042/82735022-3a4dd780-9d3c-11ea-97d5-15fec626d577.png">

**Comment by sushilshinde** [comment]
thanks @rootelement
