### ISSUE TITLE
API doesn't returns metadata for type = screeningScorecardId

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#132]
Issues: https://github.com/topcoder-platform/community-app/issues/4412

Analysis: https://github.com/topcoder-platform/community-app/issues/4412#issuecomment-633851086

**Comment by rootelement** [comment]
Not a challenge api issue. This would be pending the scorecard api release. Call v4 to get that information for now, and log it as a tech debt issue on the community app for after the scorecard api release.

**Comment by rootelement** [comment]
Sorry, related comment on other repo:
https://github.com/topcoder-platform/community-app/issues/4412#issuecomment-634099997
