### ISSUE TITLE
v5 results not matching with v4

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#142]
https://github.com/topcoder-platform/community-app/issues/4406#issuecomment-636445477

**Comment by rootelement** [comment]
This will be reviewed when migration is complete

**Comment by SathyaJayabal** [comment]
@rootelement , the past challenges displays older data first. It should return the latest challenges first.
https://api.topcoder.com/v5/challenges/?status=Completed&perPage=50&page=1

comparison with V4 : https://api.topcoder.com/v4/challenges/?status=PAST&perPage=50&page=1

**Comment by rootelement** [comment]
Please test this again @SathyaJayabal

**Comment by SathyaJayabal** [comment]
@rootelement ,the past  contests are returning the latest contests first.
