### ISSUE TITLE
Challenge Spec is missing for design challenges

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#143]
https://github.com/topcoder-platform/community-app/issues/4450

**Comment by mtwomey** [comment]
Required to resolve P0 issue: https://github.com/topcoder-platform/community-app/issues/4450

**Comment by rootelement** [comment]
Confirmed fixed. Posted on other issue
https://github.com/topcoder-platform/community-app/issues/4450#issuecomment-637084072

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/community-app/issues/4450#issuecomment-640029180

**Comment by sushilshinde** [comment]
thanks @rootelement
