### ISSUE TITLE
Tags are not returned by api

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#144]
https://github.com/topcoder-platform/community-app/issues/4449#issuecomment-636787552

**Comment by rootelement** [comment]
Tags are brought over from v4 by the technologies and platforms sections. Those are combined into the Tags on v5. Events are in the metadata object

Example of tags:
http://api.topcoder-dev.com/v5/challenges?legacyId=30056661

Example of events:
http://api.topcoder-dev.com/v5/challenges?legacyId=30051173
