### ISSUE TITLE
Challenge phases returned by api do not match V4 phases

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#146]
https://github.com/topcoder-platform/community-app/issues/4447

**Comment by rootelement** [comment]
Confirmed Fixed:
http://api.topcoder-dev.com/v4/challenges/30048648
http://api.topcoder-dev.com/v5/challenges?legacyId=30048648

**Comment by SathyaJayabal** [comment]
@rootelement , the phases are good in the  api response, but http://api.topcoder-dev.com/v5/challenges?legacyId=30048648 does not return new V5 id for the challenge, so not able to verify the phases on the challenge details page.

For example for this challenge we can see the new id returned. Which we use to create the V5 challenge detail url
https://api.topcoder.com/v5/challenges?legacyId=30108180

**Comment by ThomasKranitsas** [comment]
@SathyaJayabal I see the ID of the challenge just fine in the sample call you sent

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , I see the ID is under metadata now.

**Comment by SathyaJayabal** [comment]
@sushilshinde @ThomasKranitsas @rootelement , phases look good in dev.
<img width="1440" alt="Screenshot 2020-06-02 at 3 49 45 PM" src="https://user-images.githubusercontent.com/58783823/83509287-d28c4f00-a4e8-11ea-9478-8f449306e05a.png">

**Comment by ThomasKranitsas** [comment]
@SathyaJayabal can you please paste the API response you're getting here? I see the ID of the challenge just fine and **not** under metadata as you're saying.

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , I am sorry, it is not under metadata, but below it. Initially the id was displayed on top like in 
https://api.topcoder.com/v5/challenges?legacyId=30108180
But now (in dev) it is displayed below the meta data and so I missed it. Example:
http://api.topcoder-dev.com/v5/challenges?legacyId=30048648

Sorry for the confusion.
