### ISSUE TITLE
Migration Issues: Production Backend

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#149]
@rootelement , Many of the challenges are not present on V5 after the latest migration.

examples:
All challenges under Challenges section
https://beta-community-app.topcoder.com/community/stayhome
These two were present before, but missing after the latest migration,
https://www.topcoder.com/challenges/30126024
https://www.topcoder.com/challenges/30108180

**Comment by SathyaJayabal** [comment]
Few more examples:
https://www.topcoder.com/challenges/30120712
https://www.topcoder.com/challenges/30126528

**Comment by rootelement** [comment]
Please double check this in prod, I'm seeing them fine:
http://api.topcoder.com/v5/challenges?legacyId=30126597
http://api.topcoder.com/v5/challenges?legacyId=30126024
http://api.topcoder.com/v5/challenges?legacyId=30108180

**Comment by SathyaJayabal** [comment]
@rootelement , I can see these challenges now. 
You can see the below example was not available when last verified on Saturday.
<img width="1440" alt="migration example" src="https://user-images.githubusercontent.com/58783823/84056695-34125900-a9d4-11ea-8b25-fcf7c8564e22.png">

But now, I can see the data in api response for the same challenge. I will test the other challenges tomorrow and close this issue if they are all migrated.
<img width="1440" alt="Screenshot 2020-06-08 at 10 06 38 PM" src="https://user-images.githubusercontent.com/58783823/84056848-6e7bf600-a9d4-11ea-8ddb-3a45daa1fb9e.png">
