### ISSUE TITLE
`/v5/challenges?memberId=XXX&status=Active` returning empty data

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/challenge-api#151]
```
curl --location --request GET 'https://api.topcoder-dev.com/v5/challenges?memberId=40152905&status=Active' \
--data-raw ''
```

`40152905` is **dan_developer**

Registered in this challenge:
https://test-community-app.topcoder-dev.com/challenges/69ae395a-0a4c-4057-b480-78494005fb39

**Comment by sushilshinde** [comment]
@luizrrodrigues please open this issue on challenge-api repo

**Comment by rootelement** [comment]
This was fixed. Please close if you agree @luizrrodrigues

**Comment by luizrrodrigues** [comment]
Yep, fixed.
Thanks
