### ISSUE TITLE
Add filters for registrationOpen and startDate

### ISSUE THREAD

**Issue by simranb86** [topcoder-platform/challenge-api#163]
We should be able to filter challenges by passing flags like 
- registrationOpen (true  - all challenges which has registration phase as isOpen should be returned else false - all challenges which has registration page isOpen as false should be returned)
- startDate (return challenges where registration/challenge startDate is before provided date)

We will use this in frontend by passing combinations of the same. This helps front-end prepare meatdata for challenge listing page.

**Comment by simranb86** [comment]
blocks https://github.com/topcoder-platform/community-app/issues/4488

**Comment by rootelement** [comment]
This is fixed by additional filters. Please review the swagger.
