### ISSUE TITLE
User Registrations are not migrated from V4 to V5

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#165]
The users are registered to various challenges in V4. After migration to V5 this registration data is not carried over. For example, user dan_developer / topcoder123 is registered to 63 challenges on V4 (dev). But only a couple of challenges is returned by the V5 challenge  api for this user.

cc @sushilshinde

**Comment by SathyaJayabal** [comment]
@rootelement ,  there is disparity between the number  of registrants in V4 and V5
example:
https://www.topcoder.com/challenges?bucket=openForRegistration&filter[tracks][design]=true
https://beta-community-app.topcoder.com/challenges?bucket=openForRegistration&filter[tracks][design]=true

<img width="1440" alt="Screenshot 2020-06-25 at 11 42 54 AM" src="https://user-images.githubusercontent.com/58783823/85665627-344f6b80-b6d9-11ea-906c-ff35694d966d.png">

<img width="1440" alt="Screenshot 2020-06-25 at 11 42 17 AM" src="https://user-images.githubusercontent.com/58783823/85665562-27cb1300-b6d9-11ea-859b-b7e0b0cbd0a3.png">

**Comment by SathyaJayabal** [comment]
cc @lakshmiathreya

**Comment by rootelement** [comment]
Seems like a duplicate. Can you confirm this is fixed/closed @SathyaJayabal ?

**Comment by SathyaJayabal** [comment]
will track #201
