### ISSUE TITLE
There is no checkpoints array present in v5 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#166]
https://github.com/topcoder-platform/community-app/issues/4516#issuecomment-642988160

**Comment by rootelement** [comment]
@ThomasKranitsas isn't this information gotten from the Submissions api?

**Comment by SathyaJayabal** [comment]
Closing this as we will be handling this later
https://github.com/topcoder-platform/community-app/issues/4516#issuecomment-648194267
