### ISSUE TITLE
V4 to V5 Sync Issue: V4 Challenge Phase updates not seen in V5

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#186]
https://github.com/topcoder-platform/community-app/issues/4569

cc @lakshmiathreya

**Comment by SathyaJayabal** [comment]
Looks good now @rootelement

**Comment by SathyaJayabal** [comment]
@rootelement , Phases were synced on 25th morning IST after your update. Any phase updates that happened from teh 25th to 26th IST, are not synced to V5.

Example:
http://api.topcoder.com/v5/challenges?legacyId=30130329
http://api.topcoder.com/v4/challenges/30130329

<img width="1440" alt="Screenshot 2020-06-26 at 10 09 56 AM" src="https://user-images.githubusercontent.com/58783823/85821052-632b1780-b795-11ea-881b-f68a511a0d19.png">
<img width="1440" alt="Screenshot 2020-06-26 at 10 10 22 AM" src="https://user-images.githubusercontent.com/58783823/85821063-6aeabc00-b795-11ea-935d-b56b02cc596a.png">
cc @lakshmiathreya

**Comment by rootelement** [comment]
@SathyaJayabal Please close this here if this is fixed.

**Comment by SathyaJayabal** [comment]
@rootelement this issue is not fixed. The phases line up only when the migration script is run and not in real time as expected (with 1-5 mins lag). 


When there is any change in V4 (when review phase ends - from Online Review, Registration phase opens etc) it must reflect in real time in V5. We have been going back and forth over this many times. I think we have a misunderstanding. The previous examples which I have given works now because the migration script is run. What is not working is the  real time sync between v4 and v5 and vice versa.

Please see example below:
https://www.topcoder.com/challenges/30131013
https://beta-community-app.topcoder.com/challenges/4d8767f9-de20-4e67-b022-44badf9a7c9f
<img width="1440" alt="Screenshot 2020-07-03 at 10 46 01 AM" src="https://user-images.githubusercontent.com/58783823/86434249-9bdd6a80-bd1a-11ea-8d21-a6493fe0933f.png">
<img width="1440" alt="Screenshot 2020-07-03 at 10 46 47 AM" src="https://user-images.githubusercontent.com/58783823/86434258-a3047880-bd1a-11ea-8d49-07efc0c2f165.png">

**Comment by SathyaJayabal** [comment]
cc @lakshmiathreya @mtwomey

**Comment by lakshmiathreya** [comment]
@rootelement @mtwomey - what @SathyaJayabal is trying to emphasize is the need for v4 and v5 to be in real time sync ... this would become critical once v5 goes to Prod as legacy Apps such as Direct and OR would continue to read off v4 ... we'd continue to depend on legacy Apps for Challenge Creation and Updates even after v5 goes to Prod ... cc @sushilshinde

**Comment by lakshmiathreya** [comment]
Related - https://github.com/topcoder-platform/challenge-api/issues/204

**Comment by rootelement** [comment]
The sync is not going to be "real time". It's about 1 to 3 minutes. All the challenges you list here are in sync now. 
http://api.topcoder.com/v4/challenges/30131013
http://api.topcoder.com/v5/challenges/4d8767f9-de20-4e67-b022-44badf9a7c9f

Those phases match, everything is closed. Beyond that, i'm not sure what we can do. I can crank up the periodicity of the sync, but that's going to put a strange on v4, v5 apis and informix as it cross compares everything.

**Comment by SathyaJayabal** [comment]
@rootelement , I don't mean the 1 to 3 minutes delay. There are some phase transitions in v4 that are not synced in v5.
For example, when the review phase completes and appeals begin, this is not synced to v5. The examples contests I provide get completed by the time you check on them.

Please look at any contest in the ongoing bucket in prod which is in appeals phase. And compare the same contest in v5.

https://www.topcoder.com/challenges?bucket=ongoing
https://beta-community-app.topcoder.com/challenges?bucket=ongoing

Another example you can find is: Some challenges in production (v4) are in registration/submission phases, but are in stalled phase in V5(beta). Please check the listing pages for examples
<img width="1440" alt="Screenshot 2020-07-05 at 11 14 41 AM" src="https://user-images.githubusercontent.com/58783823/86526375-13450280-beb1-11ea-8f46-ea64d6a1125c.png">
<img width="1440" alt="Screenshot 2020-07-05 at 11 15 31 AM" src="https://user-images.githubusercontent.com/58783823/86526379-193ae380-beb1-11ea-8ace-0b13caceffb0.png">

Let us sync up on slack and  I can show you real time examples if that works for you.

**Comment by SathyaJayabal** [comment]
cc @lakshmiathreya

**Comment by rootelement** [comment]
Here's the functionality order of operations:
1. User creates a challenge in v5. Legacy processor puts this into informix via v4 api. This should take < 1min
2. Autopilot performs an action on a challenge, like reading the time on a phase and updating the status. This happens in informix. The challenge "updated" property is set to the time of that action.
3. v4 Elastic Search feeder pics up that change in informix and loads that change into Elastic Search. This could take ~5min
4. v5 Sync queue service loops through every 1 min and picks up challenges edited in the last 10 minutes to compare. If the modified date we have logged on our side doesn't match the updated date on the v4 ES side, it queues that challenge for update
5. v5 Sync processor loops through every 2 minutes (every minute divisible by 2) and pulls the challenge properties over and adds any missing resources.

So this process can take upwards of 7 or 8 minutes to perform. We can ratchet down the sync window times, but that will have to be a team effort, because I'm not positive of the system-wide impact of this.

The fact that you say by the time I see the issue, it's fixed, means that the sync is working, because i'm doing nothing other than letting the sync system run. So if the Appeals phase moves to closed that quickly, there _is_ a chance the whole system may miss that process. This is a drawback to the v4/v5 sync method and we must focus on moving autopilot to v5 systems.

The only thing I'm not sure of is the Stalled challenge status. I'm looking into that part.

**Comment by SathyaJayabal** [comment]
@rootelement, please also look at the review to appeals phase changes. It doesn't sync up to more than 24 hours, not just 7-8 mins, You can check the screenshots above. Sync happens only after appeals response completes and contest ends. We can never see a contest in appeals or appeals response phases in V5(beta). The phase is always in review and then it goes to completed. Same contest goes through  appeals and appeals response phases in v4(prod).

cc @lakshmiathreya

**Comment by lakshmiathreya** [comment]
@rootelement there are other examples too with some other phases too - 
<img width="1626" alt="Screenshot 2020-07-06 at 7 41 33 PM" src="https://user-images.githubusercontent.com/51733042/86602897-ef70e200-bfc0-11ea-8d1c-f13ca5d73043.png">
- pls see the one below:
<img width="1630" alt="Screenshot 2020-07-06 at 7 41 24 PM" src="https://user-images.githubusercontent.com/51733042/86602878-eaac2e00-bfc0-11ea-9696-e24eeb6b8321.png">

**Comment by SathyaJayabal** [comment]
@mtwomey @rootelement , we still see a lot of challenges with phases out fo sync. 
cc @lakshmiathreya 
<img width="1440" alt="Screenshot 2020-07-10 at 3 57 07 PM" src="https://user-images.githubusercontent.com/58783823/87145146-80e49a80-c2c6-11ea-8d89-aa453dcecb71.png">

**Comment by mtwomey** [comment]
James is testing fix now in dev.

**Comment by SathyaJayabal** [comment]
@rootelement , phases sync looks good so far. Will observe for a couple fo days.

cc @lakshmiathreya

**Comment by SathyaJayabal** [comment]
Phase sync looks good.

**Comment by SathyaJayabal** [comment]
Phases seem out of sync again. cc @rootelement @lakshmiathreya 
<img width="1440" alt="Screenshot 2020-07-27 at 8 37 00 PM" src="https://user-images.githubusercontent.com/58783823/88558467-321a5d00-d049-11ea-838a-003d132608b6.png">
<img width="1440" alt="Screenshot 2020-07-27 at 8 37 43 PM" src="https://user-images.githubusercontent.com/58783823/88558488-39416b00-d049-11ea-819e-3f7dc563e68c.png">
<img width="1440" alt="Screenshot 2020-07-27 at 8 38 12 PM" src="https://user-images.githubusercontent.com/58783823/88558499-3cd4f200-d049-11ea-9a94-76b3cba3437a.png">

**Comment by SathyaJayabal** [comment]
phases are good now
