### ISSUE TITLE
Challenge history data not returned for members

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#187]
https://github.com/topcoder-platform/community-app/issues/4527#issuecomment-647308330

https://api.topcoder-dev.com/v4/members/standlove/challenges/?filter=status%3Dcompleted
https://api.topcoder-dev.com/v5/challenges?memberId=310233

**Comment by simranb86** [comment]
@rootelement one more thing I noticed when combining filters there is issue in API, try these calls
`https://api.topcoder-dev.com/v5/challenges?status=Completed&track=DESIGN&type=Wireframes` and `https://api.topcoder-dev.com/v5/challenges?status=Completed&track=DESIGN&type=Wireframes&memberId=40152905`

Note: the second API call I added memberId in there and it returns [] when filters track and type being used are the one which are from challenge returned in first API call - `"legacyId": 30048664`

**Comment by simranb86** [comment]
@SathyaJayabal thanks for flagging - I added wrong API calls before, hope the above clarifies what I meant here.

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/community-app/issues/4527#issuecomment-653360312
@rootelement

**Comment by SathyaJayabal** [comment]
Api now returns completed challenges

**Comment by rootelement** [comment]
Is this still an issue? or can this be closed?

**Comment by rootelement** [comment]
@SathyaJayabal ?
