### ISSUE TITLE
Fallback to Dynamo for fetching challenge by ID

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-api#19]
If we create a challenge from the UI and we click `View challenge` immediately, the API will return 404 as the challenge does not yet exist in ES.

We need to fall back to dynamo if we're trying to fetch by ID

**Comment by ThomasKranitsas** [comment]
@cwdcwd thoughts?

**Comment by cwdcwd** [comment]
yes that's the pattern we follow for the other APIs. 
Another option is to force that update directly at the time of updation and forego the ES processor
