### ISSUE TITLE
New challenge created from TC Direct not migrated to V5

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#192]
1. Create new challenge in TC Direct
eg:https://www.topcoder.com/challenges/30130833

Expected: New challenge must be migrated and be available through in V5 challenge api
Actual: New challenge not migrated.

<img width="1440" alt="Screenshot 2020-06-23 at 5 05 30 PM" src="https://user-images.githubusercontent.com/58783823/85399059-c89fbe00-b573-11ea-91f2-7e1e329fbc89.png">
<img width="1440" alt="Screenshot 2020-06-23 at 5 05 36 PM" src="https://user-images.githubusercontent.com/58783823/85399073-cfc6cc00-b573-11ea-9e24-c23c056ee523.png">

cc @lakshmiathreya

**Comment by lakshmiathreya** [comment]
-- New Challenge Created in Prod Direct Private Group V5_Groups_11 was synced as expected to Beta (v5).
-- @rootelement - I have included you in this Group so the Challenge is visible to you as well.
