### ISSUE TITLE
Submissions not synced from v4 to v5

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/challenge-api#195]
- New Challenges created on Prod Direct are being Sync'd to v5 as expected.
- However, Submissions are not being migrated. Please see screenshots of Prod and Beta for the newly created Private Group Challenge for comparison. @rootelement - you are part of V5_Groups_11 so you could see the results below.

<img width="1629" alt="Screenshot 2020-06-25 at 5 15 50 PM" src="https://user-images.githubusercontent.com/51733042/85714395-02a1c900-b708-11ea-9222-0b14a03e2f2e.png">
<img width="1607" alt="Screenshot 2020-06-25 at 5 16 15 PM" src="https://user-images.githubusercontent.com/51733042/85714416-07667d00-b708-11ea-9286-6879e5fcbf37.png">
<img width="1678" alt="Screenshot 2020-06-25 at 5 16 31 PM" src="https://user-images.githubusercontent.com/51733042/85714426-09304080-b708-11ea-872e-17b04e73d79d.png">
<img width="1678" alt="Screenshot 2020-06-25 at 5 16 49 PM" src="https://user-images.githubusercontent.com/51733042/85714430-0a616d80-b708-11ea-917d-8e744707eb5d.png">

**Comment by rootelement** [comment]
@lakshmiathreya I believe this is fixed in the latest sync. Please close this out if so

**Comment by SathyaJayabal** [comment]
@rootelement , submissions get migrated to v5 when the migration script is run, but not in real time. What is the expected behaviour here? Is there a real time (1-5 mins lag) sync enabled for submissions made in v4 to be carried over to v5?
cc @lakshmiathreya

**Comment by lakshmiathreya** [comment]
https://github.com/topcoder-platform/challenge-api/issues/204

**Comment by SathyaJayabal** [comment]
@lakshmiathreya , @rootelement @mtwomey , this sync issue should not be a problem once we go on prod with v5 as all submissions will be made from V5. So there will not be a need for real time sync from v4 to v5. 
Same for  #201 . All registrations will be made from v5.

**Comment by mtwomey** [comment]
James is testing fix now in dev.

**Comment by lakshmiathreya** [comment]
Seems like Submissions are moving from V4 to V5 within expected time. Pls see screenshots. I made a submission via Prod - and saw it on Beta quickly. 

<img width="1631" alt="Screenshot 2020-07-14 at 2 16 47 PM" src="https://user-images.githubusercontent.com/51733042/87406652-a16e6680-c5de-11ea-9685-265bce07ec67.png">
<img width="1649" alt="Screenshot 2020-07-14 at 2 16 38 PM" src="https://user-images.githubusercontent.com/51733042/87406704-b3500980-c5de-11ea-998c-8fdb659f6d37.png">

**Comment by lakshmiathreya** [comment]
Notice that:

1. My Submissions tab is missing in Beta.
2. My handle is seen as a Registrant yet the Register button is Blue. 

These issues will be tracked separately. Closing this issues since Submissions are being synced.
