### ISSUE TITLE
Patch challenge, with timeline template, changes the type of the challenge

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-api#196]
Recently observed that patching an existing challenge with new timeline template, causes the challenges' type to be changed. Please find the developer console logs in the attached video.

[PATCH-Template-ID-changes-Type-ID.gif.zip](https://github.com/topcoder-platform/challenge-api/files/4845402/PATCH-Template-ID-changes-Type-ID.gif.zip)

**Comment by vikasrohit** [comment]
fyi @ThomasKranitsas @rootelement I am not sure if it is exactly an issue here but I am seeing this behaviour randomly when I try to test full lifecycle of challenges created via CM. It might be something we need to change in CM but we need to identify what exactly the problem is.

**Comment by ThomasKranitsas** [comment]
@rootelement This is no longer happening. We can close this issue
