### ISSUE TITLE
Community App:My Challenges bucket doesn't return all the challenges 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#211]
https://github.com/topcoder-platform/community-app/issues/4602

**Comment by SathyaJayabal** [comment]
https://api.topcoder.com/v5/challenges?memberId=MMM returns all the challenges the user is a resource of.

**Comment by SathyaJayabal** [comment]
https://api.topcoder.com/v5/challenges?memberId=MMM 
does not return all challenges of the user
user : picachui
<img width="1440" alt="Screenshot 2020-07-28 at 10 31 53 AM" src="https://user-images.githubusercontent.com/58783823/88621260-9d057b80-d0bd-11ea-8808-c0daa3e6daf0.png">
Only the 7 challenges out of the 12 are returned by the api
https://api.topcoder.com/v5/challenges?memberId=22778049&status=active

**Comment by SathyaJayabal** [comment]
cc @rootelement

**Comment by SathyaJayabal** [comment]
This will be fixed as part of #201
