### ISSUE TITLE
Track and Subtrack details incomplete/incorrect 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#214]
Subtrack details is incorrect after migration.
cc @rootelement @lakshmiathreya 

I noticed this first on dev backend  (test) yesterday and now I see it on prod backend (beta) too

<img width="1440" alt="Screenshot 2020-07-10 at 10 48 21 AM" src="https://user-images.githubusercontent.com/58783823/87119336-4e717800-c29b-11ea-8564-7b9a54f5dd3f.png">

**Comment by lakshmiathreya** [comment]
Subtrack details seem to have got migrated partially - not complete:

<img width="1658" alt="Screenshot 2020-07-10 at 11 08 35 AM" src="https://user-images.githubusercontent.com/51733042/87120306-c04ac100-c29d-11ea-9537-c5aee6de2daf.png">
<img width="1659" alt="Screenshot 2020-07-10 at 11 08 25 AM" src="https://user-images.githubusercontent.com/51733042/87120294-bb860d00-c29d-11ea-963a-d205e851bb1e.png">

**Comment by lakshmiathreya** [comment]
cc @mtwomey @sushilshinde

**Comment by SathyaJayabal** [comment]
Some of the contest also have incorrect tracks
<img width="1440" alt="Screenshot 2020-07-10 at 3 53 00 PM" src="https://user-images.githubusercontent.com/58783823/87144527-7f66a280-c2c5-11ea-8964-d19eb2334129.png">

**Comment by rootelement** [comment]
Based on our call today, I don't believe this is a blocker anymore.

**Comment by SathyaJayabal** [comment]
@rootelement , we have legacy subtracks for some challenges and new subtracks assigned for some challenges. Infact only the Data Science contests have the new subtrack `challenge`.

What is expected ?

**Comment by rootelement** [comment]
I believe this is closed here, but still open on the Community App side?

**Comment by SathyaJayabal** [comment]
yes right.
