### ISSUE TITLE
Migration Issue: Challenge duplicated during migration 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#215]
The below challenge was migrated twice 
https://www.topcoder.com/challenges/30132434
https://beta-community-app.topcoder.com/challenges/a383c5f5-9e2e-4c53-94db-ae67aca16fd0
https://beta-community-app.topcoder.com/challenges/4424fa70-9305-46a6-b052-4e2bd237f3b3
cc @lakshmiathreya 

<img width="1440" alt="Screenshot 2020-07-10 at 3 16 46 PM" src="https://user-images.githubusercontent.com/58783823/87141560-d61dad80-c2c0-11ea-90c8-a2a3eafa312c.png">

**Comment by SathyaJayabal** [comment]
@rootelement , is it possible to remove this one duplicate challenge and we can close this issue.

**Comment by SathyaJayabal** [comment]
@rootelement , found two more duplicate challenges
1.
https://beta-community-app.topcoder.com/challenges/7d2315b1-e0e8-4340-a6a6-71924562e343
https://beta-community-app.topcoder.com/challenges/bb81e459-0ba5-4635-a91a-7635ec89d6be
https://www.topcoder.com/challenges/30128733

2.
https://beta-community-app.topcoder.com/challenges/9ee0e5a3-1a27-4a5f-b4d3-28285454474e
https://beta-community-app.topcoder.com/challenges/b0a47cd8-75a7-4693-84e3-cd0ab22e63d2
https://www.topcoder.com/challenges/30128714

<img width="1440" alt="Screenshot 2020-07-28 at 12 10 49 PM" src="https://user-images.githubusercontent.com/58783823/88628345-751d1480-d0cb-11ea-8317-c28389015ca1.png">

**Comment by rootelement** [comment]
These have been removed. Please list any others you find.

**Comment by SathyaJayabal** [comment]
@rootelement , closing this  issue, We will reopen if we find any more.
