### ISSUE TITLE
User shows up in v5-resource API call but not the v5-challenges result

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/challenge-api#216]
User shows up in v5-resource API call (for a challenge), but that challenge isn't included in the v5-challenges result.

For example, you can register for a challenge and submit and you will show up in `https://api.topcoder.com/v5/resources?challengeId=XXX` but that same challenge won't be returned for that user when you call `https://api.topcoder.com/v5/challenges?memberId=MMM`.

(note from picachui: - the  `https://api.topcoder.com/v5/challenges` is calling `https://api.topcoder.com/v5/resources` on the backend)

**Comment by mtwomey** [comment]
@rootelement Another related issue for you / us to look at.

**Comment by mtwomey** [comment]
@SathyaJayabal - Ok, @rootelement and I worked through this and think we're good here now. Please check on your end. (cc: @lakshmiathreya @sushilshinde )

**Comment by SathyaJayabal** [comment]
@mtwomey @lakshmiathreya @sushilshinde @rootelement 
After registering in v5 the challenge is returned in the call
https://api.topcoder.com/v5/challenges?memberId=MMM.

The FE still doesn't display this challenge under my challenge bucket.

I am opening ticket in the community app to track this.
