### ISSUE TITLE
New challenges created in V4 are not synced to V5 after the migration (Jul 9)

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#217]
New challenges created in V4 are not synced to V5 after the latest migration
examples:
https://www.topcoder.com/challenges/30132625
https://www.topcoder.com/challenges/30132551

<img width="1440" alt="Screenshot 2020-07-11 at 9 51 59 AM" src="https://user-images.githubusercontent.com/58783823/87216333-6f4dd200-c35c-11ea-921c-8c3db8fbc242.png">

cc @mtwomey

**Comment by rootelement** [comment]
The sync was frozen. I fixed that. These challenges are showing up now. Please test. Also, please check the slack channel for more information.

**Comment by SathyaJayabal** [comment]
@rootelement, New challenges are carried over to v5 now.
<img width="1440" alt="Screenshot 2020-07-13 at 8 26 06 AM" src="https://user-images.githubusercontent.com/58783823/87266329-97673d80-c4e2-11ea-9734-f6eb5a6201f8.png">
cc @lakshmiathreya @mtwomey
