### ISSUE TITLE
The "numOfSubmissions" returned by the challenge api is incorrect

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#219]
https://github.com/topcoder-platform/challenge-api/issues/204#issuecomment-656982543

**Comment by SathyaJayabal** [comment]
cc @mtwomey

**Comment by mtwomey** [comment]
James is testing fix now in dev.

**Comment by mtwomey** [comment]
James doing final confirmation.

**Comment by mtwomey** [comment]
On the call - this one didn't have the right number of subs: https://beta-community-app.topcoder.com/challenges/0ea10b6f-c089-457b-8c08-b01be006b25e?tab=submissions

James manually sync'd it and it ok now, but will updates going forward work?

**Comment by SathyaJayabal** [comment]
Newer submissions made today are not counted.
<img width="1440" alt="Screenshot 2020-07-15 at 12 38 14 PM" src="https://user-images.githubusercontent.com/58783823/87514666-3719fc80-c698-11ea-83c9-22f9cb85d954.png">

**Comment by SathyaJayabal** [comment]
@rootelement, submissions made from both V4 and V5 show up immediately in the table. The submission count takes around 5-6 mins to catch up. But the submission count now looks good. 

Will observe a bit more and close this one.

cc @lakshmiathreya

**Comment by rootelement** [comment]
@SathyaJayabal Please re-test. I fixed the Challenge ES Processor. My tests show the number immediately update now.

I uploaded a bunch of submissions here:
https://beta-community-app.topcoder.com/challenges/0ea10b6f-c089-457b-8c08-b01be006b25e?tab=submissions

But I'm not seeing the list of submissions. is it just that challenge?

**Comment by SathyaJayabal** [comment]
@rootelement , The submissions are not displayed on the submissions tab because of a recent fix on the FE. Hoping to get that resolved soon.
https://github.com/topcoder-platform/community-app/issues/4552#issuecomment-659150945

**Comment by SathyaJayabal** [comment]
@rootelement , the number of submissions on V5 updates immediately now after a submission is made from V5. V5->V4 and V4->V5 submission count sync takes a few minutes as expected.

Will verify the submission table once the FE issue is fixed and then close this issue.

**Comment by SathyaJayabal** [comment]
Verified the submission tab.
