### ISSUE TITLE
Some completed challenges are still active in V5

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#226]
Examples:
https://beta-community-app.topcoder.com/challenges/a0459f4d-f077-43fa-a02c-cd0926fa39cb
https://beta-community-app
<img width="1440" alt="Screenshot 2020-07-20 at 11 44 38 AM" src="https://user-images.githubusercontent.com/58783823/87905717-db2beb00-ca7e-11ea-8c10-15fc38a428e5.png">
.topcoder.com/challenges/b2e65efd-d460-4ae9-a4df-65d9e85c9fd3

<img width="1440" alt="Screenshot 2020-07-20 at 11 43 29 AM" src="https://user-images.githubusercontent.com/58783823/87905640-b172c400-ca7e-11ea-9764-7aac9aa9e488.png">

**Comment by SathyaJayabal** [comment]
One more example
https://beta-community-app.topcoder.com/challenges/6b8ef58c-c01a-4da0-bdff-e4f7c349d186

Some challenges are in stalled state too. Maybe sync is frozen, @rootelement 
<img width="1440" alt="Screenshot 2020-07-20 at 12 03 34 PM" src="https://user-images.githubusercontent.com/58783823/87906878-192a0e80-ca81-11ea-8a8b-d0a837993283.png">

**Comment by rootelement** [comment]
@SathyaJayabal sync updated in prod. Please retest

**Comment by SathyaJayabal** [comment]
@rootelement, currently closed challenges are good. Let us wait a day and see if the challenges closing are synced correctly.
