### ISSUE TITLE
Number of submissions must count multiple submissions from same user as a single submission for code challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#228]
Number of submissions must count multiple submissions from same user as only as a single submission for code challenges
example:
https://beta-community-app.topcoder.com/challenges/d37dc13a-dfef-400c-aa06-970a87a1ac37?tab=submissions
https://www.topcoder.com/challenges/30133348?tab=submissions

<img width="1440" alt="Screenshot 2020-07-21 at 11 35 23 AM" src="https://user-images.githubusercontent.com/58783823/88019193-e21e3080-cb46-11ea-884d-a63691151239.png">

<img width="1440" alt="Screenshot 2020-07-21 at 11 37 21 AM" src="https://user-images.githubusercontent.com/58783823/88019277-0974fd80-cb47-11ea-82b7-91e46f66c51f.png">

**Comment by rootelement** [comment]
@SathyaJayabal this is a UI issue. The API provides the information, the UI displays it. We don't change how the data is represented for a single challenge type. CWD says that this is already implemented on v5 for Marathon Matches.

**Comment by SathyaJayabal** [comment]
Tracked on community repo
https://github.com/topcoder-platform/community-app/issues/4666
