### ISSUE TITLE
[$40] Update tests

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-api#23]
Update tests to cover the changes from https://github.com/topcoder-platform/challenge-api/commit/03d5a17aec76a68339fd2081939065b782099421

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/tcxcommunity @topcoder-platform/topcodercompetitors this is open for pickup.

PR on `develop`

**Comment by Gauravseta** [comment]
give me

**Comment by Gauravseta** [comment]
@ThomasKranitsas  https://github.com/topcoder-platform/challenge-api/pull/25 done
