### ISSUE TITLE
Duplicates on the registrants list

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#234]
example:
https://beta-community-app.topcoder.com/challenges/ad772ce5-4603-4d47-9eb5-855f7cb37e0d?tab=registrants
<img width="1440" alt="Screenshot 2020-07-23 at 11 13 22 AM" src="https://user-images.githubusercontent.com/58783823/88255254-8afa9600-ccd5-11ea-9e36-b6e9ce7a3d61.png">

**Comment by rootelement** [comment]
I _think_ this was a symptom of the sync issues we were having at the time with v5 changes being different from v4 sync'd registrants. I force-synced this one and it worked fine. I'm going to force-sync recent challenges just to make sure there are no others, but please let me know if you see any more issues

**Comment by SathyaJayabal** [comment]
Lets reopen this if we find more duplicates
