### ISSUE TITLE
Tasks assigned to a member are missing in challenge listings

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#239]
Tasks assigned to a member are displayed in V4 but not in V5. Example taas payment tasks for my handle picachui is visible in V4 but not in v5.

Also tasks where the user is an observer (or any other role) should also be displayed.

**Comment by SathyaJayabal** [comment]
The user is able to view tasks assigned to them, but not where they have other roles like observer.Reducing the priority.

example:
https://www.topcoder.com/challenges/30133255
user picachui is an observer and can see this task in V4 but not in V5.

**Comment by rootelement** [comment]
@SathyaJayabal can you retest this? Since we fixed #257 , i believe that should fix this as well?

**Comment by SathyaJayabal** [comment]
@rootelement , this one is not fixed yet. 
Same example as above
example:
https://www.topcoder.com/challenges/30133255
user picachui is an observer and can see this task in V4 but not in V5.

**Comment by SathyaJayabal** [comment]
@rootelement ,
1. A task assigned to the user  appears only under My Challenges bucket. It should also appear under Ongoing  Challenges bucket.
example:
https://www.topcoder.com/challenges/30136852
https://www.topcoder.com/challenges/30136850
https://beta-community-app.topcoder.com/challenges/46e60f21-29d2-482e-86e3-04673cee9aaa
https://beta-community-app.topcoder.com/challenges/7f7762e5-fe0c-4a9a-a361-58e60780df14
<img width="1440" alt="Screenshot 2020-08-12 at 6 48 50 PM" src="https://user-images.githubusercontent.com/58783823/90019934-b9fc9a00-dccc-11ea-96d2-8610d523db63.png">

2. Users who are  associated  with the task in other roles other than submitter role- do not see the tasks on the listings page. 
https://github.com/topcoder-platform/challenge-api/issues/239#issuecomment-671367374

cc @lakshmiathreya

**Comment by ThomasKranitsas** [comment]
1. The calls from both pages look identical.
2. Being handled in https://github.com/topcoder-platform/challenge-api/issues/280

@rootelement I think we can close this issue

**Comment by rootelement** [comment]
@SathyaJayabal please check this in prod now.

**Comment by SathyaJayabal** [comment]
@rootelement 
1. Unassigned Task: Visible to other user roles (tested for observer , copilot)
example of unassigned task - visible to picachui (copilot) and picacahuitest1(observer)
https://www.topcoder.com/challenges/75dcd9dd-772b-4ab0-b5e5-517a7a938249
Assigned task: visible only to the submitter (assigned member)


example of assigned task:
https://www.topcoder.com/challenges/906a5054-3d00-4848-b9ca-b8e2e45d91cf
assigned to : Customeruser
Not visible to  picachui (copilot) and picacahuitest1(observer)

2. Tasks should also be visible under ongoing bucket

<img width="1440" alt="Screenshot 2020-09-16 at 9 30 07 AM" src="https://user-images.githubusercontent.com/58783823/93291125-e772c100-f7ff-11ea-902c-bdb006d8127f.png">
<img width="1440" alt="Screenshot 2020-09-16 at 9 31 26 AM" src="https://user-images.githubusercontent.com/58783823/93291134-ecd00b80-f7ff-11ea-846e-9b0ddad40fcc.png">
<img width="1440" alt="Screenshot 2020-09-16 at 9 33 07 AM" src="https://user-images.githubusercontent.com/58783823/93291136-ee013880-f7ff-11ea-920e-703e94ebdd69.png">

**Comment by ThomasKranitsas** [comment]
I see the ongoing bucket has been removed. Can we close this issue? @rootelement @SathyaJayabal
