### ISSUE TITLE
Challenge counts issue

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#258]
All challenges must be a sum of Open for registration and Ongoing Challenges
<img width="1440" alt="Screenshot 2020-08-05 at 6 43 06 PM" src="https://user-images.githubusercontent.com/58783823/89417008-bce71000-d74b-11ea-8641-2936da0e23b3.png">

**Comment by ThomasKranitsas** [comment]
I'm not sure how those numbers are calculated right now but it's very easy to get the numbers with just a few calls. For example:

- http://api.topcoder.com/v5/challenges?status=Active&perPage=1 (`X-Total` is 78 which is the number of all active challenges)
- http://api.topcoder.com/v5/challenges?status=Active&perPage=1&currentPhaseName=Registration (`X-Total` is 39 which is the number of all open for registration challenges)
- The ongoing count can be `All - Open for registration`

**Comment by rootelement** [comment]
I believe this will be fixed with the updated challenge listings coming out in 1.1
