### ISSUE TITLE
Past contests : Sort by most recent

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#260]
All tasks are displayed first in Past Challenges instead of sorted by most recent.

**Comment by rootelement** [comment]
I think this is a frontend issue. There is `?sortBy=` and `?sortOrder=`

And you can `sortBy` these properties:
- 'updatedBy',
- 'updated',
- 'createdBy',
- 'created',
- 'endDate',
- 'startDate',
- 'projectId',
- 'name',
- 'typeId'

The only thing I'm sure it can't do is sort by multiple fields.

It looks like the Frontend is currently calling:
` https://api.topcoder.com/v5/challenges/?status=Completed&perPage=99&page=1`

I'm thinking it should be:
` https://api.topcoder.com/v5/challenges/?status=Completed&perPage=99&page=1&sortBy=createdBy&sortOrder=DESC` but i'm not certain on the sortOrder

**Comment by SathyaJayabal** [comment]
tracking this on the community app repo
