### ISSUE TITLE
V4 and V5 Challenge counts disparity in Admin view

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/challenge-api#261]
In V5 (Beta), the Challenge Listings shows a significantly higher count than V4 (Prod) for an Admin user. Request for a review - 
<img width="1614" alt="Screenshot 2020-08-06 at 3 35 54 PM" src="https://user-images.githubusercontent.com/51733042/89520733-f0817300-d7fb-11ea-90a2-145483031c97.png">
<img width="1633" alt="Screenshot 2020-08-06 at 3 41 15 PM" src="https://user-images.githubusercontent.com/51733042/89520740-f5462700-d7fb-11ea-9a90-0eb121db6392.png">

**Comment by lakshmiathreya** [comment]
cc @sushilshinde @Oanh-and-only-Oanh @SathyaJayabal

**Comment by ThomasKranitsas** [comment]
If you can share the code that populates those numbers, I can debug and tell you why it's wrong

**Comment by SathyaJayabal** [comment]
This can be closed @ThomasKranitsas , Admin will be able to see all tasks, hence the extra count.

cc @lakshmiathreya
