### ISSUE TITLE
Registrants list issues

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#265]
1. For this challenge we have duplicate registrants.
https://beta-community-app.topcoder.com/challenges/b22f699b-8c7b-4d67-aa77-20b00a58a657?tab=registrants
(not logged in user sees empty registrants list)

<img width="1440" alt="Screenshot 2020-08-09 at 11 55 08 AM" src="https://user-images.githubusercontent.com/58783823/89726351-59086400-da37-11ea-8100-fbc259ecc79c.png">

<img width="1440" alt="Screenshot 2020-08-09 at 11 55 25 AM" src="https://user-images.githubusercontent.com/58783823/89726387-b56b8380-da37-11ea-8d92-c766955cea1f.png">

2. One Registrant is missing in this challenge. Sync seems to be working fine and another user registered after this user was synced over correctly.
https://www.topcoder.com/challenges/30136122?tab=registrants
https://beta-community-app.topcoder.com/challenges/5e3852c9-b2a9-4d00-9e2d-4c9231b5412b
<img width="1440" alt="Screenshot 2020-08-09 at 11 52 06 AM" src="https://user-images.githubusercontent.com/58783823/89726400-cb794400-da37-11ea-8caa-3d9aae71a0a8.png">

**Comment by SathyaJayabal** [comment]
Note: challenge 2 is fine now.

**Comment by rootelement** [comment]
I agree with this being a P2, maybe even lower, because this will all go away when the public registration is via v5.

**Comment by ThomasKranitsas** [comment]
Registration is now via V5 so I think that issue is no longer valid.
@rootelement I guess we can close this one

**Comment by SathyaJayabal** [comment]
@rootelement , while this issue is not seen in current challenges, we still do have older challenges with the duplicate list of registrants. Is there a way to fix these before we close this issue.
https://www.topcoder.com/challenges/6d33bded-9b76-44ce-b478-994dd2f9b26b?tab=registrants
https://www.topcoder.com/challenges/b22f699b-8c7b-4d67-aa77-20b00a58a657?tab=registrants
https://www.topcoder.com/challenges/4bd5cf15-41ee-4932-927d-fda5731ec023?tab=registrants

**Comment by rootelement** [comment]
I've queued these to re-sync. They should be fixed.

**Comment by SathyaJayabal** [comment]
@rootelement , thanks
