### ISSUE TITLE
404 response on resource API failure

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#27]
The challenge API is oddly returning a 404 when a call to the resource API fails.  A 404 here isn't appropriate.  It should be a 403 or a 500 error, depending on the error from the resource API.  Returning a 404 is very confusing and sent me looking at the wrong stuff for a long time.  The v5 errors need to be consistent and understandable.  If we're already doing wonky stuff now, we're going to have a bad time.

Sample URL:

GET `https://api.topcoder-dev.com/v5/challenges?status=Active&page=1&perPage=50&memberId=8547899`

If you remove the `memberId` value, the call succeeds (or at least returns an empty array).

**Comment by ThomasKranitsas** [comment]
The sample API call works now.

@jmgasper can you help to reproduce this issue?

**Comment by ThomasKranitsas** [comment]
@rootelement this can also be closed
