### ISSUE TITLE
Registrants count: incorrect # of registrants displays after a user submits to a challenge

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#270]
Registrants count: incorrect # registrants displays after a user registers/submits to a challenge. The correct count is updated after a few mins after sync runs.

1. Note the # of registrants for a challenge
2.Submit to the challenge
3. Note number of registrants become equal to number of submissions (both details and listings page)
4. wait for few mins - sync updates number of registrants to correct count

cc @rootelement

**Comment by SathyaJayabal** [comment]
Adding screenshots


1.Note the # of registrants for a challenge and submit
<img width="1440" alt="Screenshot 2020-08-14 at 5 01 55 PM" src="https://user-images.githubusercontent.com/58783823/90245398-3966a680-de50-11ea-95b6-fd8f0d4d6ddd.png">
2. Note number of registrants become equal to number of submissions 
<img width="1440" alt="Screenshot 2020-08-14 at 5 02 48 PM" src="https://user-images.githubusercontent.com/58783823/90245435-4daaa380-de50-11ea-8376-0ce90083c8dd.png">

<img width="1440" alt="Screenshot 2020-08-14 at 5 03 16 PM" src="https://user-images.githubusercontent.com/58783823/90245445-526f5780-de50-11ea-81c1-ddabdcdf4631.png">

3. after few mins registrants count updated by sync
<img width="1440" alt="Screenshot 2020-08-14 at 5 12 16 PM" src="https://user-images.githubusercontent.com/58783823/90246074-6f585a80-de51-11ea-838f-c7253800d55c.png">
<img width="1440" alt="Screenshot 2020-08-14 at 5 12 43 PM" src="https://user-images.githubusercontent.com/58783823/90246091-74b5a500-de51-11ea-9892-480cbe5ab09d.png">

**Comment by ThomasKranitsas** [comment]
@rootelement this has been fixed here https://github.com/topcoder-platform/challenge-processor-es/commit/8e07388015b2e66ee2c50adad8ac89e719898824

**Comment by rootelement** [comment]
Fixed in dev. Will push out this weds night.

**Comment by rootelement** [comment]
Fixed in prod. 

![Screen Shot 2020-08-27 at 7 54 33 PM](https://user-images.githubusercontent.com/5400156/91506044-25cf2d00-e89f-11ea-93e2-19546c6077b0.png)


![Screen Shot 2020-08-27 at 7 53 54 PM](https://user-images.githubusercontent.com/5400156/91506047-2a93e100-e89f-11ea-8e58-7954ba410158.png)

**Comment by SathyaJayabal** [comment]
Verified on prod
