### ISSUE TITLE
Owner doesn't have permissions to load challenge if task is assigned to someone

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/challenge-api#272]
## Steps to reproduce

1. Create a challenge with any non-admin user, for example, with a Topcoder Manager `pshah_manager`
2. Call `GET` endpoint for the created challenge using Postman to make sure that `pshah_manager` user can see the challenge.
3. Use Postman to `PATCH` the challenge and assign task member with the next body:
   ```js
   {
     "task": {
        "isTask": true,
        "memberId": "40035291",
        "isAssigned": true
      }
   }
   ```
4. Now call `GET` endpoint again, the access would be denied:
    ```
     {
        "message": "You don't have access to view this challenge"
     }
    ```

The reason for this issue is this security check https://github.com/topcoder-platform/challenge-api/blob/develop/src/services/ChallengeService.js#L924-L929.
We should additionally allow to get tasks to the copilots.

**Comment by rootelement** [comment]
Fixed in #287
