### ISSUE TITLE
Tasks are not listed in GET endpoint for Observers

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-api#280]
As observed in https://github.com/topcoder-platform/challenge-api/issues/239#issuecomment-670372774, tasks are not returned in the list challenges endpoint when the tasks is not assigned to the logged in user and user is a non admin user. The user do exists in the resources of the challenge as Observer because the user itself created that task.

**Comment by vikasrohit** [comment]
fyi @ThomasKranitsas @rootelement

**Comment by rootelement** [comment]
Fixed in #287
