### ISSUE TITLE
Winners data missing for challenges in approval state

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#286]
Winners data missing for challenges in approval state

V4 had winners data when the challenge is in approval state. V5 is missing this data. Winners data is present only when the challenge is complete.

example challenge:
https://www.topcoder.com/challenges/6901ad3c-f107-4947-b9f0-4c1548a0bf03

**Comment by ThomasKranitsas** [comment]
https://github.com/topcoder-platform/challenge-api/blob/746dfc7421b29204bb2789ab7c8fc45008515b44/src/services/ChallengeService.js#L965-L967

The above code removes the `winners` object from the challenge if the status is not Completed

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , is it ok for winners tab  to be  displayed only after the challenge  is completed ? If so we can close this issue.

In v4, winners tab is displayed, when the challenge is in approval stage, before challenge completion.
link to community-app issue for this one https://github.com/topcoder-platform/community-app/issues/4674
