### ISSUE TITLE
Feature: When search by `name` include `tags`

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/challenge-api#316]
Issue: https://github.com/topcoder-platform/community-app/issues/5026

@rootelement We need able to include title, description in challenge specs, and tags when search by `name`

![image](https://user-images.githubusercontent.com/7029641/94853061-2eb4a080-0401-11eb-9efc-66681b5688c7.png)

**Comment by rootelement** [comment]
@ThomasKranitsas We'll need to add a `?search=` query var to search across properties. Can you think about the implications of this and list an outline here?
