### ISSUE TITLE
Challenge metadata.allowStackArt returning wrong data type

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/challenge-api#319]
ref.: https://api.topcoder.com/v5/challenges/ba800bde-a26d-486d-ac87-9db1a0b7dc9a

```
metadata: [
  name: "allowStockArt",
  value: "false",
]
```

`value` return `string` type instead `boolean`

![image](https://user-images.githubusercontent.com/7029641/94955647-46535e00-04c1-11eb-81c6-bb01e721eb8a.png)

original issue: https://github.com/topcoder-platform/community-app/issues/5037

**Comment by rootelement** [comment]
No, the metadata object is not type-specific like that. Name is always a string, Value is always a string. You'll have to typecast it on your side.

**Comment by luizrrodrigues** [comment]
@rootelement okay, I'll take care of this in FE side.
