### ISSUE TITLE
Challenge Registration - Deregistration doesn't propagate correctly

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#320]
From @SathyaJayabal 

I am testing the registration flow in dev env like we discussed in yesterday's call. Registration is working fine. But Unregistration is not reflecting in OR. When a user registers from the FE, the registration immediately reflects in OR and the user is able to see the challenge under "My Open Projects". Similarly when the  user unregisters from the FE, the user should not see the challenge in OR "My Open Projects" and not have access to the project details page in OR. But this is not happening and the user still has access to  the challenge in OR.

Example:
user: tester1234/appirio123

challenges:
https://qa-community-app.topcoder-dev.com/challenges/b6a1ea5d-8c53-46a3-8dff-33bb9ef2cf9c?tab=registrants
https://qa-community-app.topcoder-dev.com/challenges/cf5706f2-ca54-4e9c-bf57-2c3c538a24d1?tab=registrants

Note: Waited for 30 mins after unregistering- user still has access.

<img width="1440" alt="Screenshot 2020-10-02 at 9 38 32 AM" src="https://user-images.githubusercontent.com/5400156/95086666-c1e62280-06ee-11eb-9e1e-176e0b8a1ec2.png">

While the for the other challenge https://qa-community-app.topcoder-dev.com/challenges/cf5706f2-ca54-4e9c-bf57-2c3c538a24d1?tab=registrants user is still unregistered in the FE, but has access to OR.

<img width="1440" alt="Screenshot 2020-10-02 at 9 43 01 AM" src="https://user-images.githubusercontent.com/5400156/95086675-c6124000-06ee-11eb-83c4-8e20910c7c2a.png">

<img width="1440" alt="Screenshot 2020-10-02 at 9 44 45 AM" src="https://user-images.githubusercontent.com/5400156/95086685-c90d3080-06ee-11eb-9a97-3ee6055f9e6d.png">

**Comment by ThomasKranitsas** [comment]
After debugging, it seems this is the same sync/delay issue we had with challenge data.

There is some delay before the message gets posted on kafka and if the sync tool runs before the legacy resource proc deletes the resource, it'll sync the data forward and the user will get added to the challenge again.

cc @rootelement

**Comment by rootelement** [comment]
@SathyaJayabal I think Thomas is right here, I think it was because of a jam up in the resource processor. I've tried it a couple times in dev and it work fine.

**Comment by rootelement** [comment]
I'm not seeing an issue anymore. Will close. Open if any problems arise.
