### ISSUE TITLE
Add support to sortBy Prize

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/challenge-api#323]
endpoint `/challenges?sortBy=`

@rootelement Can we have option to sortBy prize?

https://github.com/topcoder-platform/community-app/issues/4982

**Comment by ThomasKranitsas** [comment]
Hey @luizrrodrigues, this is already possible. Example:
http://api.topcoder-dev.com/v5/challenges?sortBy=prizeSets.prizes.value&sortOrder=asc (highest prize first)
http://api.topcoder-dev.com/v5/challenges?sortBy=prizeSets.prizes.value&sortOrder=desc (lowest prize first)

**Comment by luizrrodrigues** [comment]
Oh, cool. Thanks @ThomasKranitsas
