### ISSUE TITLE
Filter by events (with auth) not working

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/challenge-api#325]
Endpoint: `/v5/challenges?events[]=tco20`

no auth + with `events`:
![image](https://user-images.githubusercontent.com/7029641/95522059-7909c480-09a1-11eb-91e4-bed9875ea4e4.png)

with auth + `events`:
![image](https://user-images.githubusercontent.com/7029641/95522171-bff7ba00-09a1-11eb-83cd-bbb35b7c9ea5.png)

with auth + with `events`:
![image](https://user-images.githubusercontent.com/7029641/95522205-daca2e80-09a1-11eb-813f-3f012d55a0f1.png)

with auth + random text in `events`:
![image](https://user-images.githubusercontent.com/7029641/95522385-53c98600-09a2-11eb-90aa-d12cd193aef9.png)

**Comment by ThomasKranitsas** [comment]
Hey @luizrrodrigues! This has been fixed in the latest prod release. Please test again.
cc @rootelement  (it was the same fix I did for tags)

**Comment by luizrrodrigues** [comment]
@ThomasKranitsas Yep, confirmed, this was fixed with latest Prod release.

Thanks.
