### ISSUE TITLE
sortBy not working well

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/challenge-api#326]
@rootelement 

Some sort option not working well:

`prizeSets.prizes.value` - Looks like this includes all values like Challenge Prize, Copilot and fees.
![image](https://user-images.githubusercontent.com/7029641/95807610-01a99d00-0ce1-11eb-844c-6b89642f0e92.png)

-----

`registrationEndDate` - This is a know issue, because we have multiple **Registration End** date:
- registrationEndDate _(sort using this one)_
- phases['Registration'].actualEndDate
- phases['Registration'].scheduledEndDate _(looks like right one)_
![image](https://user-images.githubusercontent.com/7029641/95807712-39184980-0ce1-11eb-87fd-09d66b1aa22a.png)

-----

`submissionEndDate` - Same here, we have multiple **Submission End** date:
- registrationEndDate _(sort using this one)_
- phases['Submission'].actualEndDate
- phases['Submission'].scheduledEndDate _(looks like right one)_
![image](https://user-images.githubusercontent.com/7029641/95808012-f145f200-0ce1-11eb-9f35-fd75f932cdc1.png)

**Comment by luizrrodrigues** [comment]
https://github.com/topcoder-platform/community-app/issues/4982

**Comment by rootelement** [comment]
This is fixed on the api side. Closing the issue.
