### ISSUE TITLE
Delete Draft Challenge

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#331]
https://github.com/topcoder-platform/challenge-engine-ui/issues/873

We need to update the WM flow to not create a Draft challenge until ready to activate if this is the case. Otherwise, unless you leave initial page where you select a track/type, the user is immediately creating a Draft challenge and won't be able to delete

**Comment by vikasrohit** [comment]
@rootelement I didn't understand the text here. Are you suggesting to keep the challenge in browser member until user hit `Save Draft` button? or something else which I didn't understand.
