### ISSUE TITLE
Challenge Track / Type association

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#34]
I'm noticing that we don't have any way to group challenge type by the selected track.  For instance, in Topcoder Direct, we have this:

<img width="591" alt="Screen Shot 2019-11-05 at 3 38 00 pm" src="https://user-images.githubusercontent.com/21790/68179028-4792b700-ffe2-11e9-85d5-89b7d9eb3226.png">

And in the new challenge UI, we have a track selector, but it doesn't change the `Type` drop down at all because there's no way to associate a type and a track, as far as I can tell.

<img width="894" alt="Screen Shot 2019-11-05 at 3 38 45 pm" src="https://user-images.githubusercontent.com/21790/68179051-5da07780-ffe2-11e9-9fdf-b6b61fb1aa04.png">

**Comment by rootelement** [comment]
We are going to simplify the Types so they apply across tracks. This isn't an issue.
