### ISSUE TITLE
No records found when searching non-active challenges by "memberId"

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/challenge-api#343]
On the Topcoder challenge listing page, we can show "My Challenges"

![image](https://user-images.githubusercontent.com/146016/100762076-3fcb5f00-33fc-11eb-9dd6-8f3a6f64f200.png)

This list provided by the next API call https://api.topcoder-dev.com/v5/challenges/?status=Active&memberId=8547899&perPage=10&page=1&sortBy=startDate&sortOrder=desc&tracks[]=Dev&tracks[]=Des&tracks[]=DS&tracks[]=QA which has `status=Active` and `memberId=8547899` (and user Bearer Token provided in header).

In the new design, we also want to show "My **Past** Challenges". List of my past challenges suppose to be retrieved by the same request but status changed to `Completed`: https://api.topcoder-dev.com/v5/challenges/?status=Completed&memberId=8547899&perPage=10&page=1&sortBy=startDate&sortOrder=desc&tracks[]=Dev&tracks[]=Des&tracks[]=DS&tracks[]=QA.

### Actual 

When we send this request **without** userer bear token it returns some list of challenges.
But if we send the send request **with** user bearer token, it reutnrs zero challenges in response.

### Expected

If we send this request **with** user bearer token, it returns past challenges of the user, defined by `memberId` param.

### Test user

I can reproduce this issue with at least 2 users `TonyJ` and `pshah_manager` on DEV environment.

### Demo video

Please, see a demo video of how I reproduce it using `TonyJ` user on DEV https://monosnap.com/file/KV63IbOCUMYgSjonD4nSrp2jmGJfGM

**Comment by ThomasKranitsas** [comment]
@maxceem can you please test again ?

**Comment by ThomasKranitsas** [comment]
@maxceem any update?

**Comment by maxceem** [comment]
Sorry for the delay with reply @ThomasKranitsas 
 
It looks good now some challenges are returned for TonyJ (id `8547899`):

![image](https://user-images.githubusercontent.com/146016/104321273-1538ef80-54ec-11eb-9a58-af97612245c1.png)

Link for verification https://www.topcoder-dev.com/challenges?bucket=myPast&tracks[DS]=true&tracks[Des]=true&tracks[Dev]=true&tracks[QA]=true&types[]=CH&types[]=F2F&types[]=TSK

**Comment by rootelement** [comment]
@maxceem can we close this?

**Comment by maxceem** [comment]
Yes, @rootelement closing it.
