### ISSUE TITLE
When creating multiple attachments in parallel, only one is actually created

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/challenge-api#348]
Follow up from https://github.com/topcoder-platform/work-manager/issues/917#issuecomment-741941747

In Work Manager, we support uploading multiple attachments at once.
- we send multiple `POST /challenges/:id/attachments` requests in parallel and all of them are successful
- but after I reload the challenge `GET /challenge/:id` returns only one attachment

See demo video https://monosnap.com/file/mVqe0igPbDIa68bUepKwRujaTU0mQN

Example challenge `29d3d66f-d87f-402f-882f-258235ac7a6f` on DEV.

**Comment by ThomasKranitsas** [comment]
PR https://github.com/topcoder-platform/challenge-api/pull/361

**Comment by ThomasKranitsas** [comment]
Deployed on dev, tested, works.

cc @rootelement

**Comment by maxceem** [comment]
@ThomasKranitsas just to clarify. The initial issue which was described in this issue still persists, if I create attachments one by one, they disappear after https://monosnap.com/file/s3fjU3J3d3d3UeS6pA3aeyT2A5aJED

After creating a demo, I've checked the PR and understood that returning the array is intentional, so I would try updating UI to use one call with an array to overcome this issue.

**Comment by ThomasKranitsas** [comment]
@maxceem that's the only way to overcome this issue. What you're talking about is the same as making multiple PUT requests at the same time. The latest one will overwrite the rest. With the latest updates, as you correctly understood, you can make one request to create multiple attachments

**Comment by vikasrohit** [comment]
@rootelement when we are planning to move this to production? Attachments feature was broken on production in WM, so I am hiding that for now and would enable it again once we have these changes in production.
