### ISSUE TITLE
Use Case - Topcoder User launching Challenge

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#358]
Right now if someone knows the v5 Project ID of an active project, and that project has a billing account, they can launch a challenge. We need to:

- [ ] Check to see if the jwt user has an active v5 Project ID
- [ ] That user has a role on that project (v5 Project.members)
- [ ] If the user has no role on the project, throw a 403

**Comment by ThomasKranitsas** [comment]
PRs:

- https://github.com/topcoder-platform/challenge-api/pull/366
- https://github.com/topcoder-platform/legacy-challenge-resource-processor/pull/19
- https://github.com/topcoder-platform/resource-processor/pull/11

cc @rootelement
