### ISSUE TITLE
WIP Use Case - v5 Project Members on Challenges

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#359]
The use case here is:
> Anybody with access to a project can launch a challenge

On the v5 Project object is a members array. Please satisfy these scenarios:
- [ ]  Complete this check #358 
- [ ]  v5 project member type `copilot` is added as a challenge manager with notifications on
- [ ]  v5 project member type `manager` is added as a challenge manager with notifications off
- [ ]  v5 project member type `customer` is added as a challenge manager with notifications off

**Comment by ThomasKranitsas** [comment]
PRs:

- https://github.com/topcoder-platform/challenge-api/pull/366
- https://github.com/topcoder-platform/legacy-challenge-resource-processor/pull/19
- https://github.com/topcoder-platform/resource-processor/pull/11

cc @rootelement
