### ISSUE TITLE
Use Case - User Added/Removed from v5 Project

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#360]
Need to update the https://github.com/topcoder-platform/resource-processor to listen to v5 Project bus messages to add/remove people as they’re added/removed from the project. Must follow all the rules set in #358 and #359

**Comment by ThomasKranitsas** [comment]
PRs:

- https://github.com/topcoder-platform/challenge-api/pull/366
- https://github.com/topcoder-platform/legacy-challenge-resource-processor/pull/19
- https://github.com/topcoder-platform/resource-processor/pull/11

cc @rootelement
