### ISSUE TITLE
V5 GET challenges API - Topgear team

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-api#364]
Topgear team reported V5 get challenges has issues
V5 GET challenges API
12:01
curl -X GET
'https://api.topcoder.com/v5/challenges?directProjectId=projectid&page=1&perPage=100'
-H 'Authorization: Bearer '
-H 'cache-control: no-cache'

Response is
{
"message": "Not found Group of id 053eb23f-......................"
}

Carried from https://github.com/topcoder-platform/work-manager/issues/898

**Comment by rootelement** [comment]
This was fixed. It was a problem with Groups pagination.
