### ISSUE TITLE
Where is the registrant list in challenge api

### ISSUE THREAD

**Issue by BenjiTheC** [topcoder-platform/challenge-api#367]
Hi team, I'm working on a academic research on crowdsourcing and is using your public api to gather some data. Just want to know that in V5 challenge API `https://api.topcoder.com/v5/challenges/?status=Completed` how can I get the list of registrants' handles? This field was available in v4 api and frontend app can show the registrants' list but I can't find any api call that contains the JSON data of registrant list.

Or is it directly return from server side rendering React?

Thank you for your help

**Comment by ThomasKranitsas** [comment]
Hey @BenjiTheC, in the V5 architecture, challenge registrants are no longer managed by the challenge API itself. They are managed by the Resources API.

Please find the documentation here http://api.topcoder-dev.com/v5/resources/docs/ (repo https://github.com/topcoder-platform/resources-api) 

Let me know if you have any further questions!

**Comment by BenjiTheC** [comment]
> Hey @BenjiTheC, in the V5 architecture, challenge registrants are no longer managed by the challenge API itself. They are managed by the Resources API.
> 
> Please find the documentation here http://api.topcoder-dev.com/v5/resources/docs/ (repo https://github.com/topcoder-platform/resources-api)
> 
> Let me know if you have any further questions!

Thank you so much @ThomasKranitsas ! Been stumbling on this for couple of days, you literally make my day!

One more question regarding the Project api. As I understand, the project api is only accessible by the project managers/co-pilot. So if project manager and co-pilot are the major stakeholder of my research, and the project data (e.g. project description, general project start/end date, etc) can be valuable, is there a way that I can apply for access of the project data via an official channel from Topcoder.com? I can provide my academic background/resume and all the docs needed to prove my purpose of research.

Thanks!

**Comment by ThomasKranitsas** [comment]
@rootelement @ajefts ☝️

**Comment by BenjiTheC** [comment]
Also during calling the challenge api and member api, I found following behaviors of microservices that I would like to provide some input for and learn the underlying design of:

1. Pagination with `page` & `perPage`, when I test the allowed value interval of pagination in different microservices, namely challenge api and member api, there seems to be an inconsistency with the behaviors of pagination.
   - `/v5/challenges` search endpoint:
      If the product of `perPage` and `page` is greater than 10,000, the endpoint will return an empty array, regardless of total number of challenges satisfied the search query (`X-Total`, `X-Total-Pages` headers). While the user will be warned when `perPage` is greater than 100, the `page` is handle silently. For example:
      ```
      https://api.topcoder.com/v5/challenges/?perPage=101&{otherQuery}
      ```
      will return an error message.
      ```
      https://api.topcoder.com/v5/challenges/?perPage=100&page=101
      https://api.topcoder.com/v5/challenges/?page=501
      ```
      will only return empty array.
      I understand that this is a behavior designed to prevent someone from abusing the use of api, but would be nice to be able to find the documentation notifying people on this.
   - `/v5/members` search endpoint:
   Comparing to challenge api, when the product of `perPage` and `page` exceeds 10,000, the api will return a 500 and error message indicating internal server error. For example
   ```
   https://api.topcoder.com/v5/members/?perPage=10&page=1001
   https://api.topcoder.com/v5/members/?page=201
   ```
   imo this should note be considered a 500 anyway, it's due to the invalid input from api user so prolly a 422? _Or maybe align the behaviors of pagination in different microservices?_ It would be a pain savior for frontend guys I believe.

2. The member api search endpoint `/v5/members` doesn't have a param to search by values of parameters like `createdAt`, so basically I can't limit the scope of searching with a range of value, like challenge api's `startDateEnd`/`endDateStart`. Besides the lack of use cases for such a search interface to exist, is there other concerns on security? Also, all return members from search are `ACTIVE` in `status` fields, does that mean all non-active members are unavailable in anyway? Or such a data will need a higher level of access to obtain?

Thanks!

**Comment by BenjiTheC** [comment]
> Hey @BenjiTheC, in the V5 architecture, challenge registrants are no longer managed by the challenge API itself. They are managed by the Resources API.
> 
> Please find the documentation here http://api.topcoder-dev.com/v5/resources/docs/ (repo https://github.com/topcoder-platform/resources-api)
> 
> Let me know if you have any further questions!

Hi Thomas, is there an api endpoint where I can access the score of a challenge submission? There used to by a `points` field in the `winners` array of the challenge in V4 api, I'm unable to find one in V5, would you please let me know, if still available, how can I get the submission score?

Thx!
