### ISSUE TITLE
Support multiple current phases

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-api#37]
We should be able to have multiple current phases at the same time. Eg submission/registration

**Comment by rootelement** [comment]
Is this relevant @ThomasKranitsas ?

**Comment by ThomasKranitsas** [comment]
yes, I believe we still need this but this will require data model updates.

Example, both the registration and submission phases can be open at the same time.

**Comment by rootelement** [comment]
How will this require data model updates? I thought we just had multiple phase objects with the isOpen flag? Do you mean because of the logic for phase changes that _that_ is preventing multiple open phases?

**Comment by ThomasKranitsas** [comment]
I'm talking about the `currentPhase` property (https://github.com/topcoder-platform/challenge-processor-es/blob/develop/src/services/ProcessorService.js#L54)

This will need to change to an array of string instead of just a string property

**Comment by rootelement** [comment]
Oh, so you can get the information, you just can't use the "convenience" property? I think that's fine, at least for now. I'll assign this to myself and consider.

**Comment by ThomasKranitsas** [comment]
Basically, this is so we can search for challenges based on the current open phase. Eg, get all challenges "open for registration".

**Comment by rootelement** [comment]
Is currentPhase a calculated property on query? Or is it stored in ES? Can we add an additional property called currentPhases (plural) and then deprecate currentPhase?
