### ISSUE TITLE
Support pure v5 tasks

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-api#378]
We need to add support for a `legacy` property named `pureV5Task` (boolean).

If that property is set on a challenge, we will skip all legacy challenge checks and handle it purely on the v5 domain.

**Comment by ThomasKranitsas** [comment]
PRs:
- https://github.com/topcoder-platform/challenge-api/pull/379
- https://github.com/topcoder-platform/legacy-challenge-processor/pull/35
- https://github.com/topcoder-platform/legacy-challenge-resource-processor/pull/20

**Comment by rootelement** [comment]
Paid out via https://www.topcoder.com/challenges/24cb81b2-b403-465e-b2d2-13b10d29399d
