### ISSUE TITLE
Defaults on Challenge Create

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#385]
The required payload for challenge create should be:
```json
{
    "status": "New OR Draft",
    "projectId": 11111,
    "name": "My Challenge",
    "typeId": "{{TYPE_TASK}}",
    "trackId": "{{TRACK_DEVELOPMENT}}",
    "timelineTemplateId": "{{TIMELINE_TEMPLATE_TASK}}",
}
```

Can you add defaults for:
- [ ] startDate - Set it to NOW if it's not present in the payload
- [ ] timelineTemplateId - can we remove that as a requirement and use the default from the API for the track/type?
- [ ] status - can we default to new if a status isn't passed?

**Comment by ThomasKranitsas** [comment]
PR https://github.com/topcoder-platform/challenge-api/pull/397
