### ISSUE TITLE
New Feature Request :  filter by prize range

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#402]
Current API endpoint doesn't support filter by prize range. Requesting this feature for the Part 2  for [challenge listing MFE](https://www.topcoder.com/challenges/ff551ab2-95cb-4acd-9343-4d490ea4bb5e) 
UI : https://marvelapp.com/prototype/g0i7agh/screen/76792761

Ref : https://docs.google.com/spreadsheets/d/1gL5KlZG9myRzw3oXEn8sHc3isvmirM5pjhfC9LQfVSE/edit#gid=0

**Comment by ThomasKranitsas** [comment]
Done. PR: https://github.com/topcoder-platform/challenge-api/pull/404

cc @rootelement

**Comment by rootelement** [comment]
Confirmed in dev:

```
curl --location --request GET 'https://api.topcoder-dev.com/v5/challenges?totalPrizesFrom=500&totalPrizesTo=4000' \
--header 'Authorization: Bearer [JWT]' \
--header 'Content-Type: application/json' \
--data-raw ''
```

**Comment by sushilshinde** [comment]
@luizrrodrigues FYI

**Comment by rootelement** [comment]
@sushilshinde @luizrrodrigues confirmed in prod
