### ISSUE TITLE
New Feature Request : Change condition

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#403]
Current API endpoint supports `Filter by Skills` but it uses AND instead OR. These need fix.
Requesting this feature for Part 2  for [challenge listing MFE](https://www.topcoder.com/challenges/ff551ab2-95cb-4acd-9343-4d490ea4bb5e) 
UI : https://marvelapp.com/prototype/g0i7agh/screen/76792761
Field  : Skills/Techology

**Comment by ThomasKranitsas** [comment]
This is already supported. We have support for a `includeAllTags` query parameter. By default, the API does an `OR` query but if you set the `includeAllTags` to `true` it switches to `AND`.

Examples:
- http://api.topcoder-dev.com/v5/challenges?tags[]=AWS&tags[]=nodejs returns challenges that have either nodejs or aws in the tags
- http://api.topcoder-dev.com/v5/challenges?tags[]=AWS&tags[]=nodejs&includeAllTags=true returns challenges that have both

cc @sushilshinde @rootelement

**Comment by sushilshinde** [comment]
@luizrrodrigues FYI
