### ISSUE TITLE
Cannot create challenges in some projects even by admin

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/challenge-api#405]
When trying to create a challenge in Work Manager in some projects there is an error:

```
Error : Project with id: 17112 doesn't exist
Please try again later and if the issue persists contact us at support@topcoder.com to resolve the issue as soon as possible.
```

This happens even using admin users like `TonyJ`, the Challenge API endpoint return error `400`: 
```js
{"message":"Project with id: 17112 doesn't exist"}
```

![image](https://user-images.githubusercontent.com/146016/112603083-28860680-8e1d-11eb-9b6a-b2e623eb98bd.png)

**Comment by rootelement** [comment]
Mentioned in thread. The project in connect needs the billing account selected.
