### ISSUE TITLE
Double payment

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#434]
@rootelement  / @ThomasKranitsas - I had a challenge that got processed for payment twice by Topcoder-X.  Not sure why yet, but there was no "block" in the challenge API either to avoid a double payment.  I'll work on the Topcoder-X side, but can we also add a check to the challenge API to avoid a double payment please?  

<img width="794" alt="Screen Shot 2021-09-09 at 6 39 58 am" src="https://user-images.githubusercontent.com/21790/132582397-9658c648-b9ac-44e9-9f1a-ee8f1f2d3933.png">

**Comment by ThomasKranitsas** [comment]
@jmgasper are you sure it's been processed twice? Do you see 2 payments in PACTs? Or was the post posted twice on Gitlab?

**Comment by jmgasper** [comment]
@ThomasKranitsas - The member received two payments in PACTs

**Comment by ThomasKranitsas** [comment]
This has been fixed today
