### ISSUE TITLE
Swagger issues

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/challenge-api#47]
Observed when working on #43 

@ThomasKranitsas Some notes from the developer:

## ChallengeTypes

- PATCH requests. In swagger, `name`, `isActive`, `abbreviation` is required. But in source code and POSTMAN they are optional

## ChallengePhases

- The model in swagger has more attributes than source code and POSTMAN
- For search, swagger defines 401 and 403 status but POSTMAN and code don't provide this

## TimelineTemplates

- The phases in Swagger are different from source code and POSTMAN
- For search, swagger defines 401 and 403 status but POSTMAN and code don't provide this
- For patch, in swagger, `name`, `isactive`, `phases` is required, but in POSTMAN and code these are optional

## ChallengeTypeTimelineTemplates

- For create and update, Swagger does not define 404 status for invalid `typeId` or `timelineTemplateId`
- For search, swagger defines 401 and 403 status but POSTMAN and code don't provide this

## Challenges

- Swagger has not defined 403 status for GET (which happens if user does not have access to the group)

**Comment by ThomasKranitsas** [comment]
Thank you @callmekatootie! I'll take it up from here
