### ISSUE TITLE
Performance fix: Update method to get groups for a user

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#477]
Performance fix: Update method to get groups for a user
https://github.com/topcoder-platform/challenge-api/pull/476

**Comment by SathyaJayabal** [comment]
verified on dev
Load time improvement:
https://docs.google.com/spreadsheets/d/1tR46uNLr0uLOEswfKvqZ1CwsBr-NAyHRB6llmehHezI/edit#gid=0
Regression testing:
https://docs.google.com/spreadsheets/d/1zHO3upydBs1dwbmdO_rhQZv9SPxKEYhE5UGpDVko7v4/edit#gid=1846865490

**Comment by SathyaJayabal** [comment]
https://topcoder.atlassian.net/browse/PLAT-236

**Comment by lakshmiathreya** [comment]
@luizrrodrigues pls link the Group gen tool to this Issue

**Comment by luizrrodrigues** [comment]
@lakshmiathreya Can you share a repo to push? (I'm can't create a new repo in `topcoder-platform`)

Currently pushed here: https://github.com/luizrrodrigues/groups-tool

**Comment by SathyaJayabal** [comment]
https://topcoder.atlassian.net/browse/PROD-933?focusedCommentId=17337
