### ISSUE TITLE
[Create challenge] the error message is not proper when the group name is invalid

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/challenge-api#50]
**Steps to reproduce:** 
 - open the Postman collection
 - send requests to create ChallengeSettings, ChallengeTypes, ChallengePhases, TimelineTemplates, ChallengeTypeTimelineTemplates if it is the first time
 - send a request creating a challenge with `groups: [" "]`

**Current result(s):**  
 - forbidden error (403 code) returns
 - group name can be arbitrary characters (like: "$@%")

**Expected result(s):**  
 - should return the validation error (400 code)
 - group name should follow some patterns

**Attachments:**  
![Untitled](https://user-images.githubusercontent.com/36178659/77723302-a654dd80-7022-11ea-8949-f1c12845634a.png)

**Comment by ThomasKranitsas** [comment]
Invalid issue
