### ISSUE TITLE
Can't update certain past challenges

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#503]
I'm attempting to apply a new tag to some historical challenges to make them easier to search / sort.

REF:  https://topcoder.atlassian.net/browse/PROD-2469

I ran into an issue with a few that the challenge API won't let me update.

I can _retrieve_ the challenges via the challenge API just fine, like:

`GET https://api.topcoder.com/v5/challenges/47621bf7-cda9-4e6d-9ac2-867fb1377298`

But, when I try to `PATCH` in the updated tags, like:

```
PATCH https://api.topcoder.com/v5/challenges/47621bf7-cda9-4e6d-9ac2-867fb1377298
{
    "tags": [
        "Marathon Match",
        "Fun Marathon Match"
    ]
}
```

I get this response from the API:

```
{
    "message": "Challenge with id: 47621bf7-cda9-4e6d-9ac2-867fb1377298 doesn't exist"
}
```

I was able to update most challenges just fine, just not the ones listed below:

### Challenge IDs:

* 47621bf7-cda9-4e6d-9ac2-867fb1377298
* c3505f21-0111-4a00-a557-865f93909dc8
* 3e7cf545-bd57-40a6-a8ac-c72786ca4a55
* 11bfd066-67fc-4996-8340-02c60fcaff1a
* f4ecc63c-d875-4e27-be0d-d9aa44877cef
* 992a9aa1-77ea-407a-9189-6f1ae26e3c11
* 18cffbc1-e04d-405c-9292-4b0d1c32858b
* 0fc3480a-9861-4ca6-9c49-5a898a8e683f
* 4485b0a9-6f29-4f92-ab75-c4c0d70983e1
* e40c763e-d5b5-47da-9fdf-306e9ac53e31
* 5f5321c7-7442-4b2b-a2a3-124fd414ce97
* 8df14f93-8af8-46ce-bf1d-ad040a6bcb32
* 4e0b403a-8220-4a27-9575-2896d4817c75
* 7545ca1c-162a-4250-b984-f5e3887e367f
* 44218a40-1775-45c3-9ad8-d3d1b3eeb044

**Comment by ThomasKranitsas** [comment]
That's because the data is missing from DynamoDB. It could be due to incomplete migration that we never caught.

If you provide the JSON bodies for those challenges based on the dynamo model definition, I can insert the data directly in dynamo from AWS

**Comment by jmgasper** [comment]
@ThomasKranitsas - I'm not sure what the format of the dynamo model is vs. what we get directly from the API.  I've exported everything individually from ES / challenge API, if that helps:

[missing_challenges.zip](https://github.com/topcoder-platform/challenge-api/files/9124669/missing_challenges.zip)

**Comment by jmgasper** [comment]
@ThomasKranitsas - Was that dump of JSON enough to fix this?  Thanks!

**Comment by jmgasper** [comment]
@ThomasKranitsas - Any update here?  Thanks!

**Comment by jmgasper** [comment]
@Oanh-and-only-Oanh ☝️

**Comment by Oanh-and-only-Oanh** [comment]
Let's proceed with this known issue.
