### ISSUE TITLE
[Create challenge] User can enter the same prize data many times

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/challenge-api#52]
**Steps to reproduce:** 
 - open the Postman collection
 - send requests to create ChallengeSettings, ChallengeTypes, ChallengePhases, TimelineTemplates, ChallengeTypeTimelineTemplates if it is the first time
 - send a request creating a challenge with `prizeSets.prizes` of some of the same items

**Current result(s):**  
 - challenge created successfully

**Expected result(s):**  
 - should validate duplicated `prizeSets.prizes` data

**Attachments:**  
![Untitled](https://user-images.githubusercontent.com/36178659/77728023-27fe3880-702e-11ea-9831-1e516aca8704.png)

**Comment by ThomasKranitsas** [comment]
I think that's fine.
Right @rootelement?

**Comment by rootelement** [comment]
Yessir, that's right @ThomasKranitsas
