### ISSUE TITLE
[ChallengeSetting] Anonymous user partially access challenge-setting routes

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/challenge-api#53]
**Steps to reproduce:** 
 - open the Postman collection
 - send requests to create ChallengeSettings, ChallengeTypes, ChallengePhases, TimelineTemplates, ChallengeTypeTimelineTemplates if it is the first time
 - go to `ChallengeSettings -> create challenge setting / or search challenge setting`, and send any requests beginning with `failure`,  => the requests are successul
 -  go to `ChallengeSettings -> get challenge setting / or update challenge setting`, and send any requests beginning with `failure`, => the requests are failure

**Current result(s):**  
- create/search routes require no authorization; while get/update require authorization for the same anonymous user

**Expected result(s):**  
- `search` and `get` routes should have the same permission

**Attachments:**  
![Untitled](https://user-images.githubusercontent.com/36178659/77732846-56811100-7038-11ea-9823-27fd1a590c32.png)

**Comment by ThomasKranitsas** [comment]
Not valid issue
