### ISSUE TITLE
Requests returning 404 code even creating/updating successfully

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/challenge-api#56]
**Steps to reproduce:** 
  - start the app with `BUSAPI_URL` pointing to the invalid address: `BUSAPI_URL=http://localhost:3002 npm start`
 - open the Postman collection
 - send a request to create , ex: ChallengeType: => 404 code will return
 - send this request again: => 409 code will return

**Current result(s):**  
 - The request entity has been created even 404 code returning

**Expected result(s):**  
- should support transaction if possible 
*(Ref: https://aws.amazon.com/blogs/developer/performing-conditional-writes-using-the-amazon-dynamodb-transaction-library/)*

**Attachments:**  
![Untitled](https://user-images.githubusercontent.com/36178659/77760295-abd51680-7068-11ea-958e-3b93118d53d1.png)

**Comment by ThomasKranitsas** [comment]
Cannot reproduce
