### ISSUE TITLE
Issue with Null values in challenge groups

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-api#58]
Based on https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html
> An array may contain null values, which are either replaced by the configured null_value or skipped entirely. An empty array [] is treated as a missing field — a field with no values.

As a temp fix, we've done the following:
https://github.com/topcoder-platform/challenge-api/blob/f5b5a21e332df606c4459335b957e7c490f64d78/src/services/ChallengeService.js#L32

**Comment by rootelement** [comment]
This has been fixed in sync/migration
