### ISSUE TITLE
v5 winners array should have userId

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/challenge-api#71]
1.  The winners array currently has handle but not userId.  Since handles can change, we should include userId as well so we don't run into trouble with lookups and data integrity.

2.  The v4 array has these fields:

submissionTime: "2019-10-14T09:28:04.000Z",
points: 100

I'm assuming they are used/helpful when displaying scores and submission times on the challenge pages.  Not sure if this can be handled another way, but just wanted to call it out.

**Comment by rootelement** [comment]
Fixed:
http://api.topcoder.com/v5/challenges/83aba4a2-2166-4672-996a-9486a9a267fb
