### ISSUE TITLE
v5 terms array missing role

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/challenge-api#73]
In v4 we have a role defined for each terms item.  The use case here is that different roles on the challenge require different terms to be signed.

{
termsOfUseId: 20704,
**role: "Reviewer",**
agreeabilityType: "Electronically-agreeable",
title: "Standard Reviewer Terms v1.0",
url: ""
},

**Comment by rootelement** [comment]
@ThomasKranitsas this might be taken care of by associating a terms resource instead of having the terms on the challenge object. We talked about that a bit ago. From Gondzo:

> terms service has the standard crud for managing terms and agreing to them, but also has feature "terms for resource" that tracks which terms are required for what resource. resource could be anything - challenge, connect project, anything really. resource is identified by reference( ie type of resource ex challenge), referenceId and tag (ex you could have separate terms for registering to a challenge and terms for submitting to a challenge - both tied to the same reference and referenceId - just another level of grouping)

> challenge api only uses the terms service to list terms, but doesn't send anything back to the terms service

>terms service isn't aware that there exists a challenge, so it's use case is quite limitted
