### ISSUE TITLE
v5 Final Submission Guidelines missing

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/challenge-api#74]
For dev challenges, we have a Description and we also have finalSubmissionGuidelines.  v5 isn't including finalSubmissionGuidelines.  This is content that is part of the spec and I think we'll need to include it.

NOTE:  I know we want to simplify this going forward, so I'm not sure if pulling over the field 1:1 is the right answer vs. doing something like appending the content to the end of the description field.

**Comment by rootelement** [comment]
@cwdcwd did you have a plan for this? We have `description` and `privateDescription` now, but i'm not sure we have the finalSubmissionGuidelines anywhere in v5 data model

**Comment by cwdcwd** [comment]
plan was to add to the existing fields and cut down on extraneous, extra fields from legacy. I didn't see any reason, from a data perspective to normalize that out to it's own field. It's not segmented/secured or searched on or manipulated. It's an additional spec bullet point

**Comment by rootelement** [comment]
This is closed. On migration, it's appended to description.
