### ISSUE TITLE
v5 total registrants and submissions

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/challenge-api#76]
Suggestion:

Add fields for the total registrants, submitters, and submissions to the response.  This will help do things like display those counts on the listing page without having to iterate through the resource lists...

Current API includes these:

checkpoints: [ ],
numberOfRegistrants: 77,
numberOfSubmissions: 33,
numberOfSubmitters: 33

**Comment by rootelement** [comment]
We have numberOfRegistrants and numberOfSubmissions.
