### ISSUE TITLE
Bug when attempting to upload attachments to a draft challenge

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#82]
Reported in https://github.com/topcoder-platform/challenge-engine-ui/issues/129

@ThomasKranitsas for `Uploading fails` the backend throw `Internal` server error when call uploading attachment api

<img width="547" alt="79996074-367f2900-84e2-11ea-9ae6-627188b2b4fd" src="https://user-images.githubusercontent.com/21790/80058586-04ff6f80-856d-11ea-88c0-45cb6acdfaa6.png">

I check the api in postman look like it require admin role for uploading the attachment

<img width="544" alt="79996218-63334080-84e2-11ea-9593-12b2aff50be1" src="https://user-images.githubusercontent.com/21790/80058599-0d57aa80-856d-11ea-9538-f645d247e24b.png">

**Comment by ThomasKranitsas** [comment]
@rootelement did you fix the access error here?

**Comment by rootelement** [comment]
Changing how attachments work in #107
