### ISSUE TITLE
Error when uploading attachments

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#84]
In the challenge-engine-UI, we are POST'ing to the `/v5/challenges/{challenge ID}/attachments` endpoint to attempt to add an attachment to a challenge.

This is currently not working, but the error message doesn't tell us anything about why.  I'm just getting a 500 status code back and this error:

`{"message":"Internal server error"}`

**Comment by rootelement** [comment]
We are reworking how attachments work using Filestack. This is captured in #107
