### ISSUE TITLE
Task support

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#95]
In the v4 API, we have a flag for items that are "tasks".  I could see that being useful in v5 to keep things streamlined.  For instance, we could update the challenge forum processor to skip creating forums for tasks.

**Comment by rootelement** [comment]
There was discussion of whittling down the "Type" to just "Challenge", "Task", or... something else. So you'd pick Design as the track, then Challenge as the Type, then everything else would be tags and metadata. That's not implemented yet.

**Comment by ThomasKranitsas** [comment]
@rootelement I guess we just need to add an entry on the seed file, right?

**Comment by rootelement** [comment]
Yes, but i'm thinking we might also need admin tools to manage this stuff going forward. I'll talk to the team about that. Can you add a type for this with a timeline template?

**Comment by rootelement** [comment]
> In the v4 API, we have a flag for items that are "tasks". I could see that being useful in v5 to keep things streamlined. For instance, we could update the challenge forum processor to skip creating forums for tasks.

To answer this specifically @jmgasper , the v5 challenge api will have no knowledge of forums. That will be it's own api and associated to a challenge, project, or other object that way.
