### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by kylewu** [topcoder-platform/challenge-api#99]
`(node:34153) UnhandledPromiseRejectionWarning: InvalidAccessKeyId: The access key ID you provided does not exist in our records.`

See this error when running `npm run test` and `npm run e2e`.

Please make sure all tests pass.

**Comment by ThomasKranitsas** [comment]
That looks related to invalid AWS configuration

**Comment by kylewu** [comment]
@ThomasKranitsas does it require a real aws account for tests? And i have aws configured with my own account although it's not asked in README

**Comment by ThomasKranitsas** [comment]
No, you don't need real aws configs. In the config file, there are some commented out configs related to AWS keys. You need to uncomment those.

Though, the tests do need to be fixed. I'm just saying that the error you're getting is related to invalid configs.

**Comment by kylewu** [comment]
@ThomasKranitsas thanks!
